Repository HYF-Class20/agile-development-group4-hyf-redesign, pull requests merged in 2023-04, with the labels that each got.

#9 Add communication file
  planning/communication.md
Labels: communication

#10 Add user personas
  planning/user-personas.md
Labels: user personas

#11 Readme
  README.md
Labels: documentation

#15 Created constrains
  planning/constraints.md
Labels: documentation

#17 Backlog
  planning/README.md
  planning/backlog.md
  planning/communication.md
Labels: documentation

#19 18-updated-backlog
  planning/README.md
  planning/backlog.md
Labels: documentation

#20 Development strategy
  planning/development-strategy.md
Labels: documentation

#21 Added update constrains
  planning/constraints.md
Labels: documentation

#24 Retrospective up
  planning/retrospective.md
Labels: documentation

#23 Add updated user persona
  planning/user-personas.md
Labels: user personas

#25 Wireframe
  planning/HYF.png
  planning/design.md
Labels: wireframe

#32 Added code
  .vscode/settings.json
  code/img/instagram-logo.jpeg
  code/img/logo.png
  code/img/program.jpg
  code/img/sponsor.png
  code/img/story1.jpg
  code/img/story2.jpg
  code/img/story3.jpg
  code/img/twitter-logo.jpeg
  code/index.html
  code/stylesheet.css
Labels: code

#36 35 volunteer page title and intro
  styles/volunteer.css
  volunteer.html
Labels: code

#44 41 volunteer footer
  styles/volunteer.css
  volunteer.html
Labels: code
